### ISSUE TITLE
2 Oxford: Create staging web site and match skin to existing site 

### ISSUE THREAD

**Issue by tonypesdm** [tonypesdm/CAMS#13]
Contact David B for url and login details of the clients existing site.

**Comment by tonypesdm** [comment]
DB checking client requirements

**Comment by joerichardsESDM** [comment]
Site uploaded to http://camswebdemo.esdm.co.uk/CAMSWeb/2.3/Staging/Oxford/standardmap.aspx

Note that the use of fixed-width images as the backgrounds for the Header & Footer means that this design does not properly support responsive design.

**Comment by tonypesdm** [comment]
Done
