### ISSUE TITLE
1 Various data submit faults in survey submit code

### ISSUE THREAD

**Issue by tonypesdm** [tonypesdm/CAMS#15]
1)	AdminArea value is not being submitted correctly. The nature of the submission varies. 
o	For the following submission types, an example submission would be:  “Llanbadoc Community|362” – it needs to drop the  “|362” from the submission value – **Fault in submit code**
Description	Entity	RecordType	Example HoldingID
Assigned Survey: New furniture + good condition	Infra	Insert	3005
Assigned Survey: New furniture + good condition	InfraCondition	Insert	3006
Assigned Survey: New furniture + bad condition + issue	Infra	Insert	3007
Assigned Survey: New furniture + bad condition + issue	InfraCondition	Insert	3008
Assigned Survey: New furniture + bad condition + issue	Maint	Insert	3009
Assigned Survey: New Issue	Maint	Insert	3010
Assigned Survey: Edit furniture condition (Bad)	InfraCondition	Insert	3017
Assigned Survey: Edit furniture condition (Bad)	Maint	Insert	3018

Note that the fault is in the submit code - I think

  <data>
    <CAMSData>
      <entity>Infra</entity>
      <recordType>Insert</recordType>
      <recordUserID>03FC0BEE-1480-429C-AC0B-265CF7773F11</recordUserID>
      <adminAreaGroup>Llanbadoc Community|362Usk Community|383</adminAreaGroup>
      <dateSubmitted>2016-11-17T17:05:29</dateSubmitted>
      <dateOccurred>2016-11-17T17:05:29</dateOccurred>
      <recordGUID>574636af-b1b9-4729-a73e-923fa220a018</recordGUID>
      <parentGUID>00000000-0000-0000-0000-000000000000</parentGUID>
    </CAMSData>
    <infra>
      <InfraCode />
      <InfraType>2</InfraType>
      <GroupTypeDescr>Alongside</GroupTypeDescr>
      <TypeDescr>Alongside/Barbed</TypeDescr>
      <AdminArea>362Usk Community</AdminArea>
      <AdminAreaDescr>Llanbadoc Community</AdminAreaDescr>
      <OnRoute />

o	The following submission is not getting the AdminArea and just submitting the literal ‘[AdminAreaGroup]’ instead – **Fault in submit code**
Description	Entity	RecordType	Example HoldingID
Request an update	Maint	AddUser	3004

2)	The following values are not submitting the Priority or PriorityDescr values (even though they request them on the web form) – **Add Priority to the submit code**
Description	Entity	RecordType	Example HoldingID
Assigned Survey: New furniture + bad condition + issue	Maint	Insert	3009
Assigned Survey: Edit furniture condition (Bad)	Maint	Insert	3018

4)	Completed Assigned Path Surveys and Completed Assigned Issues does not refresh after submission and continues to display the confirmation when trying to submit a new record (a manual page refresh is needed). **Fault in code**
5)	For the following submission the submitted workcode value within xml is not right - should be the surveycode, seems to be submitting a random number instead. Example submission: **Fault in code**
Description	Entity	RecordType	Example HoldingID
Assigned Survey: Reject Task	Work	Route	3021

6)	On the ‘Complete Assigned Issue’ form we are exposing 'assigned to web user' as part of values list - should just be complete or incomplete. I’ve got a feeling this was previously hardcoded just to these 2 values… **What view is used – should we be creating a new LUT and associated view – eg TaskStatusLUT?**

8)	The following submissions are placing the landcode value under RouteCode. Value needs to be moved under landcode. **The following script in the ascx forms is not working:
            if (ESDM.CAMS.Forms.getParentType() == 4) {
                ESDM.CAMS.Forms.autoSetFields("[ParentCode],Form_InfraNew_Officer_Infra_LandCode_tbx");
            } else {
                ESDM.CAMS.Forms.autoSetFields("[ParentCode],Form_InfraNew_Officer_Infra_RouteCode_tbx");
            }**
Description	Entity	RecordType	Example HoldingID
Officer: New furniture + good condition (on LAND)	Infra1	Insert	3027
Officer: New furniture + bad condition + issue (on LAND)	Infra1	Insert	3030

11)	The following submissions did not submit a parent value. Would expect them to submit either a Landcode or Routecode value within the Infra node – This is on purpose to avoid inadvertently sending the wrong value.  **The field should not be required because it is an update**
Description	Entity	RecordType	Example HoldingID
Officer: Edit furniture + good condition (on ROUTE)	Infra1	Update	3031
Officer: Edit furniture + good condition (on LAND)	Infra1	Update	3032
Officer: Edit furniture + bad condition + issue (on ROUTE)	Infra1	Update	3033
Officer: Edit furniture + bad condition + issue (on LAND)	Infra1	Update	n/a

**Comment by joerichardsESDM** [comment]
Investigated 1. Could not recreate a circumstance where the data recieved from the WMS is of the form Llanbadoc Community|362Usk Community|383. With regard to example 3004 submitting the literal ‘[AdminAreaGroup]’ , this is because the javascript is defined in the WMS template file \map\templates\maintData.htm and is using placeholders which aren't being substituted by the WMS, probably because the fields do not exist on the view. (TP aware and going to look at the database)

**Comment by joerichardsESDM** [comment]
Looked at 2. Added Priority to the submission handler. PriorityDescr is not a field on the Form_InfraNew_Survey or Form_InfraEdit_Survey forms.

**Comment by joerichardsESDM** [comment]
Fixed 3. Looked at 5: the form currently uses vieWeb_WorkAssignmentActionTypeLUT to populate the drop-down list. Would probably be best to create a separate view.

**Comment by joerichardsESDM** [comment]
Looked at 4, couldn't replicate this. Example 3021 is a rejected task - all the ones I tried passed the correct values.

**Comment by joerichardsESDM** [comment]
looked at 6; it is working fine for me, submitting the following JSON with a LandCode:

"Infra": {
    "RouteCode": "",
    "LandCode": "00221",
    "WKTPoint": "POINT(338653.77998168947 221667.23500305176)",
    "AdminArea": "359",
    "Easting": "338653.780",
    "Northing": "221667.235",
    "InfraType": "4",
    "DateInst": "02/12/2016",
    "Name": "",
    "OnRoute": 0,
    "LRO": 0
  },

**Comment by joerichardsESDM** [comment]
Looked at 7; Added Landcode/Routecode to Infra submission of Form_InfraEdit_Officer

**Comment by tonypesdm** [comment]
Done
