### ISSUE TITLE
1 HTTPS mixed content error on standardmap.aspx when run under https

### ISSUE THREAD

**Issue by tonypesdm** [tonypesdm/CAMS#16]
Mixed Content: The page at 'https://camswebdemo.esdm.co.uk/CAMSWeb/2.3/Staging/Demo/standardmap.aspx' was loaded over HTTPS, but requested an insecure image 'http://camsapidemo.esdm.co.uk/4.0/Staging/Demo/WMS/v6.41/scripts/mapserv.ex…N=1.1.1&layer=Routes&REQUEST=getlegendgraphic&FORMAT=image/jpeg&SCALE=9999'. This content should also be served over HTTPS.

**Comment by joerichardsESDM** [comment]
Fixed on Demo site

**Comment by tonypesdm** [comment]
tested ok
