### ISSUE TITLE
1 Form_MaintEdit_Officer.ascx syntax error on AssignedTo

### ISSUE THREAD

**Issue by tonypesdm** [tonypesdm/CAMS#17]
Appears to be when the field value is null

jquery-1.11.3.min.js?version=2.3.6172.28068:2 Uncaught Error: Syntax error, unrecognized expression: #Form_MaintEdit_Officer #Form_MaintEdit_Officer_Maint_AssignedTo_ddl option[value=]
    at Function.ga.error

**Comment by joerichardsESDM** [comment]
The issue was due to the code that populates the dropdown lists not accounting for the fact that the incoming data may be null. I have wrapped the offending lines in a check for null data and now the dropdown will default to 'Please Select' if the incoming value is empty.

**Comment by tonypesdm** [comment]
Tested ok
