### ISSUE TITLE
2 Show Current Location needs to check if https, if not give a sensible message

### ISSUE THREAD

**Issue by tonypesdm** [tonypesdm/CAMS#19]
Device location requests can only be made from secure pages, so if the site is http, then a suitable message should be displayed instead of the normal 'Unable to get location!' message.  ie 'Get Location will only work under https, please contact the system administrator.'

ESDM.js?version=2.3.6172.28068:12 getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Comment by joerichardsESDM** [comment]
Changed this and published on Demo.

**Comment by tonypesdm** [comment]
Tested - ok
