### ISSUE TITLE
1 IE11 My Tasks Edit furniture/issue popups fail to appear(using map edit buttons), Info popup can appear off map

### ISSUE THREAD

**Issue by tonypesdm** [tonypesdm/CAMS#22]
Info popup is not centring map correctly, so form is running off screen

Check 50m message is appearing when the users tries to place an issues more than 50m from a ROW.

Survey:
If click on edit furniture or edit issue, then open form – goes to a blank page displaying the word ‘false’

**Comment by joerichardsESDM** [comment]
Fixed the problem with the popups not appearing. This required a couple of edits to the javascript.en.resx file and the regeneration of the resourse dlls. I have only done this on the Demo site - will need care when rolling this fix into the client sites, may be safer though more time consuming to do all the edits manually.
