### ISSUE TITLE
1 Add a javascript method to expand and collapse sections of text

### ISSUE THREAD

**Issue by tonypesdm** [tonypesdm/CAMS#28]
Provide example html on Kent site, eg with a +Help 'button'

**Comment by joerichardsESDM** [comment]
I've added this.

To use it, to need to wrap the text you want to hide in an element (I've used a <div> in the example below but it could be a <p> or any other block element) Then add another element before this with class='accordion'. This is the element that gets clicked on to show or hide the text. Whatever text you put in this element (Instructions in my example) is always visible.

eg:
<div class="accordion">Instructions</div>
<div>The map shows all of the Public Rights of Way and Open Access Land in the County. To report a problem select the 'My Reported Problems' menu item.</div>
