### ISSUE TITLE
1 Kent: Apply interface improvements requested on 5/12

### ISSUE THREAD

**Issue by tonypesdm** [tonypesdm/CAMS#30]

**Comment by tonypesdm** [comment]
Joe:
Change button style to purple
Increase size of data input fields
Ensure the selected menu item is highlighted
Expandable sections – move + closer to Help and ensure the grey section highlight is even around + Help
Change Request materials to a 2 column format – see client ideas
Change Activity Record format – see client ideas

**Comment by joerichardsESDM** [comment]
Fixed these issues.

**Comment by tonypesdm** [comment]
done
