### ISSUE TITLE
Missing values in submitted xml for existing issue updates (Maint Update submissions) + Similar issue applies to Web 2.2

### ISSUE THREAD

**Issue by richardcesdm** [tonypesdm/CAMS#47]
Page: My Tasks
Area of functionality: Assigned survey
Form: Edit existing issue

Description: 
Missing values in submitted XML (descr values not essential but useful) in Web 2.3:
LogDate
LogBy
LogByDescr
AssignedTo
AssignedToDescr
PriorityDescr
Reason

In addition, web 2.2 is missing all of the above plus
Priority

**Comment by joerichardsESDM** [comment]
Added Nil=True attribut to empty nodes in Maint XML

**Comment by richardcesdm** [comment]
resolved
