### ISSUE TITLE
Remove case sensitivity for userID

### ISSUE THREAD

**Issue by richardcesdm** [tonypesdm/CAMS#49]
Page: Any that depends on userID to filter records / map features
Area of functionality: User filtering

Description: Tried to introduce a filter to the issues that are displayed on the map to set them only to show where the user has reported them. Unfortunately we have a mix of upper and lower case userID's. 

Currently the UserID expected by the web seems to be lower case, whilst the actual ID values as held in the CAMS db are all uppercase.

Please can you remove this case sensitivity?

**Comment by richardcesdm** [comment]
Further to above - it may be possible to resolve this just be ensuring the RecordUserID values that are submitted on every type of submission are submitted in upper case.

Whilst the case sensitivity is at the web end, if it proves impossible / very difficult to resolve we could implement a fix database side to force all values into lower case. This would involve changing many different views though so if a single change is possible web side that would be best.

**Comment by tonypesdm** [comment]
The most solid fix is to ucase the GUID when it is passed to a string variable or added to a url.  Can you add a GetGUID function(that upper cases te GUID) that is always used to assign the GUID to a string/url.

Change all references to the GUID to use this method in code.
Ucase all GUID strings in the holding table - how can we do this - the value is in the xml

**Comment by joerichardsESDM** [comment]
I've replaced all references to the ProviderUserKey in CAMSweb with a call to a central method that returns an upper-cased String value.

I've also run the following database query to rectify lower-case ID's already stored in the web-holding table:
UPDATE [CAMS-Web-Demo-Staging].[dbo].[webHolding]
SET [XMLText].modify('replace value of (/webData/data/CAMSData/recordUserID/text())[1] with xs:string(upper-case((/webData/data/CAMSData/recordUserID/text())[1]))')

**Comment by tonypesdm** [comment]
Must update the UserID validation in the mapserver maint.inc file to use upper case.

**Comment by richardcesdm** [comment]
Warwick: I need to know how to apply this.

**Comment by tonypesdm** [comment]
All OK 27.feb/17
