### ISSUE TITLE
error with ol37.js (Possibly Warwick specific, lower priority)

### ISSUE THREAD

**Issue by richardcesdm** [tonypesdm/CAMS#50]
**Page:** My Reported Problems
**Area of functionality:** Selecting a record on the grid to display on map

**Browser:** Internet Explorer 11 running in Edge mode (Tested and does not occur in Chrome)

**Description:** After selecting a previously reported issue (does not matter if issue has been processed or not) it will generate approx 25 instances of the following error. Selecting another record from the grid will then generate another 25ish errors. Does not seem to effect functionality. 

**Example (error taken from console in IE):**
SCRIPT5022: IndexSizeError
File: ol37.js, Line: 257, Column: 291
SCRIPT5022: IndexSizeError
File: ol37.js, Line: 257, Column: 291

(repeats)

**Comment by joerichardsESDM** [comment]
Resolved with fixed StandardMap.js
