### ISSUE TITLE
Warwick specific: styling issue with Priority field

### ISSUE THREAD

**Issue by richardcesdm** [tonypesdm/CAMS#51]
**Page:** Officer map (page6)
**Form:** New issue / Update issue

**Description:** The priority field is being cut off - the edge of the field needs to end before the edge of the form, currently it runs off the edge. Must be due to Warwick specific styling as not occuring on staging demo system (or anywhere else)

**Example:** [Image](http://i.imgur.com/IN0WcC2.png)

**Comment by tonypesdm** [comment]
Drop down list css styling modified to allow auto sizing up to 100% of assigned width

**Comment by richardcesdm** [comment]
tested and ok
