### ISSUE TITLE
Searching for the value "///" (or any term with the "/" character) produces error

### ISSUE THREAD

**Issue by richardcesdm** [tonypesdm/CAMS#53]
**Page:** Any

**Description:** When searching in Town, Street Name or Postcode with the value "///" it produces a page alert stating 'search error'. This is in addition to the normal feedback message that is displayed underneath the search box. 

Encountered when accidentally searching for a path (357/85/1) in the Town search. Seems to be specific to the / or \ characters. Regex?

**Comment by tonypesdm** [comment]
RegEx added on all fields except RouteCode to filter out invalid characters, eg ///

**Comment by richardcesdm** [comment]
Returns error message of "Please enter a search term of more than two characters" when searching for /// - need to update resx

**Comment by richardcesdm** [comment]
tested and ok
