### ISSUE TITLE
Issues not displaying on printable survey form (& elsewhere)

### ISSUE THREAD

**Issue by richardcesdm** [tonypesdm/CAMS#55]
**Page:** My Tasks (SurveyDetails.aspx and issuedetails.aspx)

**Description:** Select a assigned survey path that has existing issues. Then select the view/print button. On the subsequent page the existing issues will be highlighted with pink circle but issue icon does not display.

Also: This problem only effects SurveyDetails.aspx in CAMS Web 2.3. However it also effects issuedetails.aspx in CAMS Web 2.2 - so if you could identify where this is switched on/off that would be appreciated! Assuming it is config but I don't know where (and can't find in documentation)

**Example:** Login with richardc@esdm.co.uk (same pw) and on my tasks select route with ID 374/103/1 - has 2 issues attached that do not show on print page.

**Comment by joerichardsESDM** [comment]
The maps on SurveyDetails.aspx & issuedetails.aspx don't seem to have any configurability of layers. Instead they show the default layers plus any that are hardcoded on the page itself. As the Overlay_Maint is not a default layer, it doesn't show up onSurveyDetails.aspx, so I have added it on the page itself.

**Comment by richardcesdm** [comment]
Warwick: n/a

**Comment by tonypesdm** [comment]
Resolved end Feb
