### ISSUE TITLE
Warwick 'search error' problem

### ISSUE THREAD

**Issue by richardcesdm** [tonypesdm/CAMS#58]
Following on from Elaine's steps we are able to reproduce a search error. Will likely need to try and recreate in our staging system to trace

**Comment by tonypesdm** [comment]
I can't recreate, can we check the data for Maint record PROW321104 when we next connect.  Once the Search fix has been applied, is the fault still reproducible?

**Comment by joerichardsESDM** [comment]
Superseded by #65
