### ISSUE TITLE
1 W Sussex: New Issues are being created with PROW ids>1000000.  These then fail to be found on Track a Problem

### ISSUE THREAD

**Issue by tonypesdm** [tonypesdm/CAMS#60]
Check WebHolding table for records submitted with web tracking no > 999999.  eg 1013493 or 1072578.

Note that I cannot see any records with web tracking nos>999999 on the demo db.

Is this a sproc problem?  The Ids should run from 100000 to 999999 (I think?)

**Comment by joerichardsESDM** [comment]
The Web Tracking number is generated by the following database stored procedure: [usp_GetWebTrackingNo]

**Comment by tonypesdm** [comment]
Updated GetWebTrackingNo sproc
