### ISSUE TITLE
1 W Sussex: My Tasks new Maint & Infra fail to submit

### ISSUE THREAD

**Issue by tonypesdm** [tonypesdm/CAMS#61]

**Comment by joerichardsESDM** [comment]
Ruled out problem in client-side code and in submission handler code. Will have to check if there is logging available on the API

**Comment by joerichardsESDM** [comment]
Checked API logs, no errors being thrown. Will need to create a custom API build with additional logging to really  get under the skin of what is happening

**Comment by joerichardsESDM** [comment]
I found the issue: the Submit Handler was choking when the incoming AdminAreaGroup was empty, which all the West Sussex ones are. I have put a check in the code to handle this scenario, but you may also want to ensure the view is populated with the AdminAreaGroup value.

**Comment by tonypesdm** [comment]
Tested OK
