### ISSUE TITLE
1 API errors on Find a Fault and Manage My Account

### ISSUE THREAD

**Issue by tonypesdm** [tonypesdm/CAMS#62]
Goto manage my account: Forbidden API error
When not logged in, Find Fault: ‘ Invalid command sent to ExecuteXmlReader.  The command must return an Xml result.’

**Comment by joerichardsESDM** [comment]
Invalid command sent to ExecuteXmlReader requires the stored procedure [usp_getWebHoldingDataByWebTrackingNo] to be updated with a 'FOR xml AUTO' statement appended to the end of the final SELECT statement.

**Comment by joerichardsESDM** [comment]
Forbidden API error was because West Sussex API wasn't at latest version 4.6.0.4 with Upper-case user ID fixes

**Comment by tonypesdm** [comment]
Tested OK
