### ISSUE TITLE
1 Oxford:Tidy landscape/portrait PDF formats

### ISSUE THREAD

**Issue by tonypesdm** [tonypesdm/CAMS#63]
Vertically centre the PDF address and logo on landscape and Portrait. Also fit the Logo to the box(see Oxford A4 Portrait)

**Comment by joerichardsESDM** [comment]
I've sorted out the header layout and also cleaned up a lot of unnecessary code which should speed up PDF creation. NB - this handler is shared code & isn't client specific.

**Comment by joerichardsESDM** [comment]
Vertically centred the address & logo. Also refactored address code so it doesn't add blank lines if the address is < 5 lines long

**Comment by tonypesdm** [comment]
Tested OK
