### ISSUE TITLE
Double click on username/role when logged in as test_xg has stopped working

### ISSUE THREAD

**Issue by tonypesdm** [tonypesdm/CAMS#64]
Since the GUID update to upper case:
Uncaught TypeError: $(...).val(...).ToUpper is not a function
    at Object.getUserId (ESDM.CAMS.js?version=2.3.6257.23217:30)
    at HTMLDivElement.ondblclick (standardmap.aspx:232)

**Comment by joerichardsESDM** [comment]
Fixed but not yet deployed to demo server

**Comment by joerichardsESDM** [comment]
Fix deployed to all Staging sites

**Comment by tonypesdm** [comment]
Tested OK - works for all roles
