### ISSUE TITLE
Trace data problem with web search

### ISSUE THREAD

**Issue by richardcesdm** [tonypesdm/CAMS#65]
Best see me when you get to this one - I'll need to forward you the email from client with the exact sequence of required steps to reproduce.

**Comment by joerichardsESDM** [comment]
Initial investigations have narrowed down the actions required to replicate:
1. Go to 'Report a Problem', search for a place that will return more than one result
2 Go to 'Track a Problem', search for a place that will return more than one result

This affects all sites, not just Warwick

**Comment by joerichardsESDM** [comment]
Fixed.

**Comment by richardcesdm** [comment]
tested and ok
